INSERT INTO AUTHOR VALUES (1, 'Ramesh');
INSERT INTO AUTHOR VALUES (2, 'Khilan');
INSERT INTO AUTHOR VALUES (3, 'kaushik');
INSERT INTO AUTHOR VALUES (4, 'Chaitali');
INSERT INTO AUTHOR VALUES (5, 'Hardik');
INSERT INTO AUTHOR VALUES (6, 'Komal');
INSERT INTO AUTHOR VALUES (7, 'Muffy');